CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(190) NOT NULL UNIQUE,
	phone VARCHAR(32) NULL,
	password_hash VARCHAR(255) NOT NULL,
	role ENUM('PATIENT','DOCTOR','ADMIN') NOT NULL DEFAULT 'PATIENT',
	name VARCHAR(120) NULL,
	avatar_url VARCHAR(255) NULL,
	status ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
	last_login_at DATETIME NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




















